# Generated by Django 3.2.16 on 2023-01-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('product_availablity', models.BooleanField()),
                ('product_discount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.productcategory')),
            ],
        ),
    ]
